//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringThesis.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngineeringThesis.UI.Resources.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kontrahenta.
        /// </summary>
        public static string AddContractor {
            get {
                return ResourceManager.GetString("AddContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj fakturę.
        /// </summary>
        public static string AddInvoice {
            get {
                return ResourceManager.GetString("AddInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sprzedawcę.
        /// </summary>
        public static string AddSeller {
            get {
                return ResourceManager.GetString("AddSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres firmy.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwagi.
        /// </summary>
        public static string CompanyComments {
            get {
                return ResourceManager.GetString("CompanyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa firmy.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres firmy.
        /// </summary>
        public static string ContractorAddress {
            get {
                return ResourceManager.GetString("ContractorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa firmy.
        /// </summary>
        public static string ContractorName {
            get {
                return ResourceManager.GetString("ContractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahenci.
        /// </summary>
        public static string Contractors {
            get {
                return ResourceManager.GetString("Contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń kontrahenta.
        /// </summary>
        public static string DeleteContractor {
            get {
                return ResourceManager.GetString("DeleteContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń fakturę.
        /// </summary>
        public static string DeleteInvoice {
            get {
                return ResourceManager.GetString("DeleteInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń sprzedawcę.
        /// </summary>
        public static string DeleteSeller {
            get {
                return ResourceManager.GetString("DeleteSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj kontrahenta.
        /// </summary>
        public static string EditContractor {
            get {
                return ResourceManager.GetString("EditContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj fakturę.
        /// </summary>
        public static string EditInvoice {
            get {
                return ResourceManager.GetString("EditInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj sprzedawcę.
        /// </summary>
        public static string EditSeller {
            get {
                return ResourceManager.GetString("EditSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wystawienia.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer faktury.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string NIPNumber {
            get {
                return ResourceManager.GetString("NIPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data płatności.
        /// </summary>
        public static string PaymentDeadline {
            get {
                return ResourceManager.GetString("PaymentDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regon.
        /// </summary>
        public static string RegonNumber {
            get {
                return ResourceManager.GetString("RegonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedawca.
        /// </summary>
        public static string SellerName {
            get {
                return ResourceManager.GetString("SellerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedawcy.
        /// </summary>
        public static string Sellers {
            get {
                return ResourceManager.GetString("Sellers", resourceCulture);
            }
        }
    }
}
